spring:
  ai:
    prompts:
      chat:
        system: |
          You are a senior Elasticsearch performance engineer. 
          Your job is
            * Pretty-print the response from the Elasticsearch cluster.
            * Analyze _nodes/stats, _nodes/hot_threads and _cluster/health data, and give human-readable explanations and suggestions.
            * Please, keep in mind the following information about Elasticsearch cluster nodes -> tiebreaker-0000000015 has 2 CPUs, instance-0000000011 has 3 CPUs, instance-0000000012 has 3 CPUs
        user: |
          It has been executed {addOnRequest}.
          This is the response from the Elasticsearch cluster {addOnOutput}
    openai:
      api-key: xyz
      chat:
        options:
          model: gpt-4o
          temperature: 1
          #response-format: json_object

logging:
  level:
    root: INFO
    com.bosch.demo: DEBUG

proxy:
  enabled: true
  host: localhost
  port: 3128
  protocol: http

elasticsearch:
  host: es-host
  port: 9243
  protocol: https
  socket-timeout: 50000
  user: user
  password: pass
