spring:
  ai:
    prompts:
      chat:
        system: |
          You are a senior Elasticsearch performance engineer. 
          Your job is
            * Analyze _nodes/stats, _nodes/hot_threads and _cluster/health data, and give human-readable explanations and suggestions.
            * When you are ready with the formatting and analysis, please always respond with structured JSON in this format
              { 
                "name-of-the-elasticsearch-request": "_nodes/stats",
                "formatted-elasticsearch-response": "Here is a pretty-printed version of the response from the Elasticsearch",
                "analysis-and-suggestions": "Your Analysis and Suggestions"
              }
        user: |
          Context: Please, keep in mind the following information about Elasticsearch cluster nodes ->  has 2 CPUs,  has 3 CPUs,  has 3 CPUs
          It has been executed {addOnRequest}.
          This is the response from the Elasticsearch cluster {addOnOutput}
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o
          temperature: 0.3
          top-p: 0.7
          max-tokens: 2000

logging:
  level:
    root: INFO
    com.bosch.demo: DEBUG

proxy:
  enabled: true
  host: ${PROXY_HOST}
  port: ${PROXY_PORT}
  protocol: http

elasticsearch:
  host: ${ES_HOST}
  port: 9243
  protocol: https
  socket-timeout: 50000
  user: ${ES_USER}
  password: ${ES_PASSWORD}
